print("Nume, prenume: Sanduleac Loredana")
print("Data si anul nasterii: 07.08.2004")
print("Adresa ( domiciliu ): str.Alexandr Puskin 29 ap.43")
print("Telefon de contact: +37360548861")
print("Email: lorisanduleac@gmail.com")
print("Studii: 2011-2015 - Etapa primara in IPLT Mihai Eminescu")
print("        2015-2020 - Etapa gimnaziala in IPLT Mihai Eminescu")
print("        2020-prezent - Etapa liceala in IPLT Mihai Eminescu")
print("Succese si reusite obtinute: Diploma de gradul I la olimpida scolara la franceza")
print("                             Diploma de gradul I la olimpida scolara la ed tehnologiica")
print("                             Diploma de gradul II la olimpida scolara la istorie")
print("Competente aditionale: Microsoft Word, Excel, PowerPoint, Internet")
print("Cunoasterea limbilor: limba romana-limba nativa, limba rusa-fluent, limba engleza-B2, limba franceza-B1")
print("Interese: muzica, literatura, cinematografia")
print("Calitati: responsabilitate, abilitati de comunicare, empatie, calitati de lider, toleranta")